### ISSUE TITLE
Add aliases to snippets

### ISSUE THREAD

**Issue by Haysamawan** [BuildTheEarth/main-bot#113]
This would make it easier to organise snippets, and easier for users to run commands.
For example, if there is a snippet called `@cbbxd`, the alias could be `cbbxd`, and we wouldn't have to make another snippet for it.

**Comment by Haysamawan** [comment]
how do i make this a feature request, idk how to use github lmao

**Comment by cAttte** [comment]
bruh that's already a thing (#13), check `=help snippets`
