### ISSUE TITLE
Notify of banned builders

### ISSUE THREAD

**Issue by MrFluffy-BTE** [BuildTheEarth/main-bot#117]
Add a feature to our bot that makes it send a notification to a channel when a builder gets perma banned, so a senior reviewer can go remove their solo claim or a RBTL can go kick them out of their build team.
I don’t know how many builders we’ve perma banned in the past, but I don’t think all of the mods know their claim needs to be deleted as well (Since they are officially kicked from the project), and that kinda concerns me.

Author: Danmiko#0980

**Comment by fnionn** [comment]
So would this need to check if the user who was banned had a specific role?

**Comment by mebrooks01** [comment]
yes 
it would need to check if the user had the builder role (691343715117039666)

**Comment by cAttte** [comment]
(please don't hardcode the id, just use `hasRole(Roles.BUILDER)`). also, where would the notification be sent?

**Comment by mebrooks01** [comment]
could be sent to some channel in BTE Team Owners if we add the bot to that server and or sent reviewer server private but as for that part I think you should check with @MrFluffy-BTE and Mabey salty

**Comment by fnionn** [comment]
> (please don't hardcode the id, just use `hasRole(Roles.BUILDER)`). also, where would the notification be sent?

Yeah, I'll add it into the .yml

**Comment by cAttte** [comment]
nope, it shouldn't be in the config, because roles are tracked [by](https://github.com/BuildTheEarth/main-bot/blob/main/src/struct/discord/GuildMember.ts#L10) [name](https://github.com/BuildTheEarth/main-bot/blob/main/src/util/roles.ts). also, we're not adding the bot to yet another server, so let's just make it send it to #reviewer-committee or whatever (i will ask Someone)

**Comment by fnionn** [comment]
> nope, it shouldn't be in the config, because roles are tracked [by](https://github.com/BuildTheEarth/main-bot/blob/main/src/struct/discord/GuildMember.ts#L10) [name](https://github.com/BuildTheEarth/main-bot/blob/main/src/util/roles.ts). also, we're not adding the bot to yet another server, so let's just make it send it to #reviewer-committee on the main server or whatever (i will ask Someone)

Ok, will do that.

**Comment by fnionn** [comment]
Added in #[#aa96e18](https://github.com/BuildTheEarth/main-bot/commit/aa96e1830da42caafd93656ec4ea67facb90cd9b)
