### ISSUE TITLE
Moderation command for adding notes to members

### ISSUE THREAD

**Issue by cAttte** [BuildTheEarth/main-bot#12]
from @arc25275:
> What if there was a way to add notes to people

ideally, each member could have one moderation note, which can be edited/cleared by any moderator/manager. for example:

- `=note @non alt of @non2`
- `=note edit @non alt of @non2, likes to make edgy jokes`
- `=note clear @non`

the note would be shown under the user's case records (`=check @non`).

additionally, if a moderator tries to add a note to a member which already has one, it could be added after a newline (instead of requiring the moderator to run `=note edit`).

---

the possibility of there being multiple notes for each member has been rejected; the added complexity of note IDs is unwanted. this could be avoided by letting each moderator have a note for every member, but ideally, moderators should be able to edit other's notes—which would add yet another layer of complexity. a "crowdsourced" note was found the best fit for this feature.

**Comment by HPaulson** [comment]
Having multiple notes seems fairly easy here, actually. You wouldn't need note IDs or anything of the sort.

I'd simply have an Array of notes for each user, and use the note's index as it's "id";
You could have a command `=note @user`, which would show an embed with all the notes in the array- and their Index.
The staff member could then `=note edit @user <index>` to edit a note by its index, which they'd know from the command above;
To add a note `=note add @user whatever text`, would add to the Array
To delete a note `=note del @user <index>`

This would be extremely easy to implement and would be pretty nice for staff members;

**Comment by cAttte** [comment]
@HPaulson the "added complexity" was on the moderators' side. of course, it wouldn't be hard to actually implement it, but the whole "`edit`/`add`/`del` by ID/index" thing was rejected by one of the mod managers (olive) since most of the time we won't even need multiple notes!

if you'd like to submit a PR, just make sure to create a new entity like `ModerationNote`, have the two `edit` and `clear` subcommands, and add the note as an extra field to the `=check` command

**Comment by HPaulson** [comment]
Ah I understand. Initially I had misinterpreted this as "the added complexity of using [storing] note IDs", rather than being on the moderators side.

Sorry for the confusion!
