### ISSUE TITLE
Staff suggeston #229

### ISSUE THREAD

**Issue by MrFluffy-BTE** [BuildTheEarth/main-bot#121]
Have a bot system to prevent users joining the server with NSFW names. Saves moderators a lot of time.

Author: Gabe™#1111

**Comment by rudeyeti** [comment]
Catte is already doing this through a moderation bot, but he's busy.

**Comment by cAttte** [comment]
yes, this will be part of [cop](https://github.com/cAttte/cop) ([policeman](https://github.com/BuildTheEarth/policeman)), but i'm busy with more important bots so this will take a couple of months lol
