### ISSUE TITLE
Snippet aliases

### ISSUE THREAD

**Issue by cAttte** [BuildTheEarth/main-bot#13]
from @arc25275:
> can you make it so we can make snippet aliases

the `=snippet` command would expose another sub-command, `aliases` (which could have an `alias` alias!), with ~~two~~ \*three other sub-sub-commands: `add`, `remove` \*and `list`. for example:

- `=snippet aliases add welcome en hi`

a downside is that the syntax is pretty confusing; `aliases` is a sub-command, `add` a sub-sub-command, `welcome` the snippet name, `en` the snippet language, and *then*, `hi`, the alias itself.

\*edited

---

edit: perhaps, aliases could work this way:

aliases under the `en` (default) language should act as "global" aliases:

-   `=name` → "hello"
-   `=snippet aliases add name en alias`
-   `=alias` → "hello"
-   `=alias es` → "hola"

aliases under specific languages should work as shorthands to those name/language combinations:

-   `=name` → "hello"
-   `=snippet aliases add name es nombre`
-   `=nombre` → "hola"

the language could be overridden when provided:

-   `=nombre de` → "hallo"

edit!: the distinction of *English aliases acting as global ones* is redundant, since that's exactly how aliases in other languages work (including the *overriding language* part)

**Comment by cAttte** [comment]
yeah!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by metalcupcake5** [comment]
Added in c375f7881b3658926effa8efc7677dbe0a5c1447
