### ISSUE TITLE
Notify reviewers if a Builder is banned from the main server.

### ISSUE THREAD

**Issue by Coppertine** [BuildTheEarth/main-bot#141]
There can be cases where claims are left dormant due to the user who claimed it being banned afterwards. An easy solution to this is to check if a user with the Builder role is banned to then message to `691351327950766161` (Review Committee Private) so that Reviewers can delete all claims that are under that user on the website.

**Comment by mebrooks01** [comment]
Duplicate #114

**Comment by mebrooks01** [comment]
* #117
