### ISSUE TITLE
Advanced builder role is not removed after 3 months

### ISSUE THREAD

**Issue by XylotrupesGideon** [BuildTheEarth/main-bot#175]
the advanced builder role is supposed to be removed after 3 months.
Currently this is not the case. and people have negative days until the role is taken away.

![grafik](https://user-images.githubusercontent.com/31574542/120192442-76ebc300-c21b-11eb-9cf2-854128347b95.png)

would be nice to have this working.
Thx

**Comment by cAttte** [comment]
oops, looks like i forgot to `schedule()` on start-up like with the other schedulable entities
