### ISSUE TITLE
Schedule entity abstract class

### ISSUE THREAD

**Issue by cAttte** [BuildTheEarth/main-bot#198]
So Many Schedules!!!!! we should have an abstract class called something like `ScheduleEntity` or `SchedulableEntity` that can be extended by the current `AdvancedBuilder`, `BannerImage`*. `Task`, `TimedPunishment`, [`Reminder`](174) (and future) entities. so that we don't have to repeat methods and properties like `undo()` or `undoTimeout` Every Single Time.

*maybe not this one, though, because it works differently than the rest: it has more of a "global" (static) scheduler that manipulates individual rows as it pleases, instead of requiring to schedule every instance of the entity independently. adding this system to the abstract class would probably not be worth it if it is only used by this sub-class.

**Comment by XboxBedrock** [comment]
@arc25275 @mebrooks01 Do we even want this anymore considering how much the scheduled entities have diverged?

**Comment by mebrooks01** [comment]
I dont think it is worth the time to implement for how little of an impact it will practically make. It will just create more bugs to solve while only serving to give a slight performance boost.
