### ISSUE TITLE
All contributors

### ISSUE THREAD

**Issue by cAttte** [BuildTheEarth/main-bot#20]
this is the issue where you can add yourself (or someone else) as a [contributor](https://github.com/BuildTheEarth/main-bot#Contributors) to the project, with the all-contributors bot.

**Comment by cAttte** [comment]
@all-contributors please add @cAttte for code

**Comment by cAttte** [comment]
@all-contributors please add @cAttte for code

**Comment by cAttte** [comment]
@all-contributors please add @vicrobex for design!

**Comment by cAttte** [comment]
@all-contributors please add @arc25275 for ideas!

**Comment by cAttte** [comment]
@all-contributors please add @metalcupcake5 for code!

**Comment by cAttte** [comment]
@all-contributors please add @cAttte and @noahhusby for project management!

**Comment by cAttte** [comment]
@all-contributors please add @noahhusby for project management!

**Comment by cAttte** [comment]
@all-contributors please add @olivephio for ideas :)

**Comment by cAttte** [comment]
@all-contributors also add @olivephio for design

**Comment by cAttte** [comment]
@all-contributors add @fnionn for infrastructure, code

**Comment by arc25275** [comment]
@all-contributors add @arc25275 for code
