### ISSUE TITLE
Add a command to modify punishment length

### ISSUE THREAD

**Issue by cAttte** [BuildTheEarth/main-bot#27]
probably something like `=extend` and `=reduce`, or maybe even inside `=case edit`; `=case edit length <id> <new length> <reason>`.

normally, punishment lengths are extended because either, (a) the user broke another rule while being muted/banned, or (b) the moderators decided on a fairer punishment.

for the first scenario, the extension should be added as a separate punishment, while for the second one, it should just be an actual _extension_. whether the distinction between these two should be significant hasn't been decided.

**Comment by jkPngu** [comment]
Why not use a unique id to edit the case, in addition you could review the case =case review <id>;
Just to give mods a overview; 
Hopefully that helped

**Comment by HPaulson** [comment]
@jkPngu I agree; All cases could be put into an array, and you could use their index++ as their "ID". Just make sure not to remove any cases from the array. Any cases that are "removed" (unsure if BTE does this but still applies) can just be marked as such instead of revoked from the array;

**Comment by jkPngu** [comment]
@HPaulson , its also really useful and dynamic.

**Comment by rudeyeti** [comment]
All cases already have a numerical id, so that's how they're edited.

**Comment by jkPngu** [comment]
Will the addition of review command come into place, if moderators would like to see the reason for punishment, who gave them the punishment ect. I believe that might be added already but if not

**Comment by cAttte** [comment]
> Why not use a unique id to edit the case, in addition you could review the case =case review ;
Just to give mods a overview;
Hopefully that helped

> I agree; All cases could be put into an array, and you could use their index++ as their "ID". Just make sure not to remove any cases from the array. Any cases that are "removed" (unsure if BTE does this but still applies) can just be marked as such instead of revoked from the array;

please see the [ActionLog](https://github.com/BuildTheEarth/main-bot/blob/main/src/entities/ActionLog.ts) entity to see how these are stored.

> Will the addition of review command come into place, if moderators would like to see the reason for punishment, who gave them the punishment ect. I believe that might be added already but if not

there is a [case](https://github.com/BuildTheEarth/main-bot/blob/main/src/commands/case.ts) command, which lets moderators see the reason and other details for a specific case.
