### ISSUE TITLE
Add moderation placeholders

### ISSUE THREAD

**Issue by mebrooks01** [BuildTheEarth/main-bot#293]
create punishment reason place holders 
so instead of
'=kick <user> please change your username and comeback'
its 
'=kick <user> %username%'

**Comment by XboxBedrock** [comment]
I swear i have like half written classes for this that are not implemented

**Comment by XboxBedrock** [comment]
also will use same syntax as support bot ({{e}})

**Comment by mebrooks01** [comment]
oop

**Comment by mebrooks01** [comment]
added with commit `fff8d0b` thx arc

**Comment by arc25275** [comment]
Still waiting on full implementation from Xbox for placeholders working in moderation commands

**Comment by XboxBedrock** [comment]
pushed
