### ISSUE TITLE
Double space edit snippet

### ISSUE THREAD

**Issue by frikandelworst** [BuildTheEarth/main-bot#368]
**Describe the bug**
The succes message of the edit snippet command contains a double space before the language.

**To Reproduce**
1. Run /snippets edit

**Expected behavior**
There not being a double space.

**Screenshots**
![image](https://github.com/BuildTheEarth/main-bot/assets/66461508/07a3be12-abbd-4147-9cb7-fa412e4156ab)

**Additional context**

**Comment by Nudelsuppe42** [comment]
`Edited tpll snippet in en.`
Cant see a double space 🤔

**Comment by frikandelworst** [comment]
> `Edited tpll snippet in en.`
> 
> Cant see a double space 🤔

Between "in" and "en"? Or am I going crazy 🤔

**Comment by Nudelsuppe42** [comment]
> > `Edited tpll snippet in en.`
> > Cant see a double space 🤔
> 
> Between "in" and "en"? Or am I going crazy 🤔

I think? 
![image](https://github.com/BuildTheEarth/main-bot/assets/67996941/c690b6fd-e097-491d-8b3e-ba7051ad2986)

**Comment by cAttte** [comment]
there is clearly a double space in the screenshot

**Comment by XboxBedrock** [comment]
Your discord is doing weird stuff, no code points to there being a double space and my client does not show it either
