### ISSUE TITLE
Port suggestions to main server + various enhancements

### ISSUE THREAD

**Issue by arc25275** [BuildTheEarth/main-bot#4]
- [x] Port suggestions to main server
- [x] Anonymous suggestions
- [ ] Suggestion management commands

**Comment by cAttte** [comment]
> Port suggestions to main server

solved by 5e54d3b

**Comment by cAttte** [comment]
> - [x] Anonymous suggestions

solved by bdf06cf

**Comment by cAttte** [comment]
> - [ ] Automatically create, edit, and tag issues in a github repo from suggestions on bot
> - [ ] Automatically comment on said issues based on answers to the suggestion

moved to #14

**Comment by cAttte** [comment]
i fucked up the commit but anyways, good riddance 😎
