### ISSUE TITLE
Add a way to publish weekly reports in staff server to #updates

### ISSUE THREAD

**Issue by arc25275** [BuildTheEarth/main-bot#41]
A `=publish` with a message link argument. It should only be usable by managers, and on messages in #weekly-updates.

Example:

> **Weekly update from @arc25275:**
> - *Annoyed catte with bot ideas*
> - *Implemented **x** suggestion*
> - *Made **x** change to support*

Alternatively, it should be usable with messages outside of weekly updates, such as announcements, but I would need to talk to the admins and managers.

**Edit:** Yeti had a better idea: Listen to a ✅ reaction to publish.

**Comment by mebrooks01** [comment]
would be very pog
