### ISSUE TITLE
Verified Content Creator Role Command

### ISSUE THREAD

**Issue by mebrooks01** [BuildTheEarth/main-bot#42]
A command to add or remove the verified content creator and verified streamer role from users
`=cc <add | remove> <vcc | vs> <ID>`
to run the command you should require the `PR Subteam Leads` or `PR Content Creation Team` roles.

Just moving this hear instead of burred in some dev chat were a mentioned it

**Comment by cAttte** [comment]
i might just make the existing `teamOwner` command a `promote` command with dynamic roles depending on the author's position (RBTL, CC Lead...)

**Comment by cAttte** [comment]
@mebrooks01 hey, the command is now `position` (alias `vcc`, `bto`), here's the usage info:

-   `=position <member> ['bto' | 'vcc' | 'vs'] ['promote' | 'demote']`

you can specify the position (it will default to Verified Streamer for you, so make sure to specify it), and `promote` or `demote`, like this:

-   `=vcc @user vcc demote`
