### ISSUE TITLE
Add a report feature for the no of suggestions

### ISSUE THREAD

**Issue by XylotrupesGideon** [BuildTheEarth/main-bot#47]
It would be great if a suggestion report could be generated for the last 7 days.

Usage: (allowed for Suggestion role, Staff)
=suggestion report [time (default=7d)] 

Desired output:
```
In the last 7 days # suggestions have been made.
# Suggestions were approved
# Suggestions were denied
# Suggestions are currently in progress.
```
in progress would include suggestions that are "in-progress", "forwarded" and "more-info"

Why?
1. We want to formalize the Management  weekly reports and this would help the automation
 2. For users that are curious about the suggestion progress

**Comment by cAttte** [comment]
i'll add this. since we're also adding moderation reports, i don't know if i should add all of them into a single `report` command (e.g., `=report tasks`, `=report moderation`, `=report suggestions`...)

**Comment by XylotrupesGideon** [comment]
I think tha thaving it separated would be a bit better that way people can choose what they are interested in.

**Comment by cAttte** [comment]
yeah, it's a different bot, but I could probably connect to its database somehow (but i'll see if it's doable since the bot is not even ours)

**Comment by XylotrupesGideon** [comment]
Yeah it is honestly not a big think as we can just count the number of logs for the bot to get the number pretty quickly.

**Comment by cAttte** [comment]
anyways this all is going into the [statistics bot](https://github.com/BuildTheEarth/statistics-bot) (to be released in 8 years), and there's no need to transfer it there because it's a pretty basic/broad objective
