### ISSUE TITLE
make it possible to check multiple people at once

### ISSUE THREAD

**Issue by yukij8** [BuildTheEarth/main-bot#52]
title self explanatory

**Comment by cAttte** [comment]
ok i will add this next year because i'm lazy :trollface:

**Comment by yukij8** [comment]
sounds good uwu

**Comment by XboxBedrock** [comment]
Wdum by "check"

**Comment by cAttte** [comment]
[`=check`](https://github.com/BuildTheEarth/main-bot/blob/main/src/commands/check.ts)

**Comment by XboxBedrock** [comment]
ah, makes sense

**Comment by cAttte** [comment]
nevermind this is probably not that useful and kinda confusing :trollface: sorry
