### ISSUE TITLE
Sub-suggestion management not working

### ISSUE THREAD

**Issue by XboxBedrock** [BuildTheEarth/main-bot#59]
Today someone was trying to edit their sub-suggestion, it wouldn't let them do it for some reason, so I, as the author of the main suggestion, tried editing the sub suggestion, the bot said it worked, but it edited the main suggestion.

**Comment by cAttte** [comment]
i'll fix this later, probably with a static `Suggestion.parseNumber()` method or something

**Comment by cAttte** [comment]
a bit later than expected but :trollface:
