### ISSUE TITLE
Add server banner queue/periodic changing

### ISSUE THREAD

**Issue by cAttte** [BuildTheEarth/main-bot#85]
from [#brainstorming](https://discord.com/channels/690908396404080650/790040321626603580):

> [obnoxious whining about server banner not being updated]

– #pogress

> guys would you like the banner to be periodically updated by the bot
> like every week or something like that

– me

> YES

– someone

> [irrelevant conversation]

– people

> yes the queue sounds like a brilliant idea with managers and admins being able to add things to the queue
> uh and a log or something that we can see what was put in the queue by whom...
> Uh and at the same time a post should be made in updates that announces the change and specifies the builder that made the build so we give credit to the builders as well...
> i would imagine the command to add the build to the queue to be
> `=banner add <image_link> | <place_name> | <Builders> | [fun fact/story/description]`
> 
> The #update post could then be something along the lines of:
> 
> We have a new banner:
> **[place name]** by **[Builders]**
> [Fun fact/story/description]
> 
> *If you want your build to be featured make sure to post it in [#showcase](https://discord.com/channels/690908396404080650/692259936012468235)*

– xylo

---

too tired to write meticulous constitution about each and every single feature, technical detail, and downside this feature would have but hopefully you got the memo

**Comment by mebrooks01** [comment]
> YES
> _–_ someone 
that was me smh

**Comment by cAttte** [comment]
right
